// Ce fichier est généré automatiquement pour l'import statique des 100 premières nourritures
// du fichier Nourriture.json. Il permet d'importer les images et d'exporter un tableau utilisable dans NourriturePage.jsx.

// Imports dynamiques générés ci-dessous :
import taro_sauce_jaune1 from './images/taro_sauce_jaune1.jpeg';
import taro_sauce_jaune2 from './images/taro_sauce_jaune2.jpeg';
import taro_sauce_jaune3 from './images/taro_sauce_jaune3.jpeg';
import taro_sauce_jaune4 from './images/taro_sauce_jaune4.jpeg';
import taro_sauce_jaune5 from './images/taro_sauce_jaune5.jpeg';
import taro_sauce_jaune6 from './images/taro_sauce_jaune6.jpeg';
import taro_sauce_jaune7 from './images/taro_sauce_jaune7.jpeg';
import taro_sauce_jaune8 from './images/taro_sauce_jaune8.jpeg';
import taro_sauce_jaune9 from './images/taro_sauce_jaune9.jpeg';
import taro_sauce_jaune10 from './images/taro_sauce_jaune10.jpeg';
import taro_sauce_jaune11 from './images/taro_sauce_jaune11.jpeg';
import taro_sauce_jaune13 from './images/taro_sauce_jaune13.jpeg';
import taro_sauce_jaune14 from './images/taro_sauce_jaune14.jpeg';
import taro_sauce_jaune15 from './images/taro_sauce_jaune15.jpeg';
import taro_sauce_jaune16 from './images/taro_sauce_jaune16.jpeg';
import taro_sauce_jaune17 from './images/taro_sauce_jaune17.jpeg';
import taro_sauce_jaune18 from './images/taro_sauce_jaune18.jpeg';
import taro_sauce_jaune19 from './images/taro_sauce_jaune19.jpeg';
import taro_sauce_jaune20 from './images/taro_sauce_jaune20.jpeg';
import ndole1 from './images/ndole1.jpeg';
import ndole2 from './images/ndole2.jpeg';
import ndole3 from './images/ndole3.jpeg';
import ndole4 from './images/ndole4.jpeg';
import ndole5 from './images/ndole5.jpeg';
import ndole6 from './images/ndole6.jpeg';
import ndole7 from './images/ndole7.jpeg';
import ndole8 from './images/ndole8.jpeg';
import ndole9 from './images/ndole9.jpeg';
import ndole10 from './images/ndole10.jpeg';
import ndole11 from './images/ndole11.jpeg';
import ndole12 from './images/ndole12.jpeg';
import ndole13 from './images/ndole13.jpeg';
import ndole14 from './images/ndole14.jpeg';
import ndole15 from './images/ndole15.jpeg';
import ndole16 from './images/ndole16.jpeg';
import ndole18 from './images/ndole18.jpeg';
import ndole19 from './images/ndole19.jpeg';
import ndole20 from './images/ndole20.jpeg';
import eru1 from './images/eru1.jpeg';
import eru2 from './images/eru2.jpeg';
import eru3 from './images/eru3.jpeg';
import eru4 from './images/eru4.jpeg';
import eru5 from './images/eru5.jpeg';
import eru6 from './images/eru6.jpeg';
import eru7 from './images/eru7.jpeg';
import eru8 from './images/eru8.jpeg';
import eru9 from './images/eru9.jpeg';
import eru10 from './images/eru10.jpeg';
import eru11 from './images/eru11.jpeg';
import eru12 from './images/eru12.jpeg';
import eru13 from './images/eru13.jpeg';
import eru14 from './images/eru14.jpeg';
import eru15 from './images/eru15.jpeg';
import eru16 from './images/eru16.jpeg';
import eru17 from './images/eru17.jpeg';
import eru18 from './images/eru18.jpeg';
import eru19 from './images/eru19.jpeg';
import eru20 from './images/eru20.jpeg';
import kous_kous1 from './images/kous_kous1.jpeg';
import kous_kous2 from './images/kous_kous2.jpeg';
import kous_kous3 from './images/kous_kous3.jpeg';
import kous_kous4 from './images/kous_kous4.jpeg';
import kous_kous5 from './images/kous_kous5.jpeg';
import kous_kous6 from './images/kous_kous6.jpeg';
import kous_kous7 from './images/kous_kous7.jpeg';
import kous_kous8 from './images/kous_kous8.jpeg';
import kous_kous9 from './images/kous_kous9.jpeg';
import kous_kous10 from './images/kous_kous10.jpeg';
import kous_kous11 from './images/kous_kous11.jpeg';
import kous_kous12 from './images/kous_kous12.jpeg';
import kous_kous13 from './images/kous_kous13.jpeg';
import kous_kous14 from './images/kous_kous14.jpeg';
import kous_kous15 from './images/kous_kous15.jpeg';
import kous_kous16 from './images/kous_kous16.jpeg';
import kous_kous17 from './images/kous_kous17.jpeg';
import kous_kous18 from './images/kous_kous18.jpeg';
import kous_kous19 from './images/kous_kous19.jpeg';
import kous_kous20 from './images/kous_kous20.jpeg';
import okok1 from './images/okok1.jpeg';
import okok2 from './images/okok2.jpeg';
import okok3 from './images/okok3.jpeg';
import okok4 from './images/okok4.jpeg';
import okok5 from './images/okok5.jpeg';
import okok6 from './images/okok6.jpeg';
import okok7 from './images/okok7.jpeg';
import okok8 from './images/okok8.jpeg';
import okok9 from './images/okok9.jpeg';
import okok10 from './images/okok10.jpeg';

export const nourrituresStatic = [
  // Les 100 premiers objets du JSON, adaptés pour l'import statique
  { id: 1, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune1 },
  { id: 2, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune2 },
  { id: 3, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune3 },
  { id: 4, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune4 },
  { id: 5, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune5 },
  { id: 6, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune6 },
  { id: 7, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune7 },
  { id: 8, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune8 },
  { id: 9, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune9 },
  { id: 10, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune10 },
  { id: 11, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune11 },
  { id: 12, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune13 },
  { id: 13, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune13 },
  { id: 14, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune14 },
  { id: 15, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune15 },
  { id: 16, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune16 },
  { id: 17, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune17 },
  { id: 18, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune18 },
  { id: 19, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune19 },
  { id: 20, nom: 'taro_sauce_jaune', description: "Le taro sauce jaune est un plat camerounais préparé avec des racines de taro cuites dans une sauce épaisse à base de tomates et d'épices.", ingredients: "Le taro est une racine riche en glucides et en fibres, souvent cuisinée avec des tomates, des oignons et des épices pour créer une sauce savoureuse.", imageUrl: taro_sauce_jaune20 },
  { id: 21, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole1 },
  { id: 22, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole2 },
  { id: 23, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole3 },
  { id: 24, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole4 },
  { id: 25, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole5 },
  { id: 26, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole6 },
  { id: 27, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole7 },
  { id: 28, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole8 },
  { id: 29, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole9 },
  { id: 30, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole10 },
  { id: 31, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole11 },
  { id: 32, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole12 },
  { id: 33, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole13 },
  { id: 34, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole14 },
  { id: 35, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole15 },
  { id: 36, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole16 },
  { id: 37, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole18 },
  { id: 38, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole18 },
  { id: 39, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole19 },
  { id: 40, nom: 'ndole', description: "L'ndole est un plat traditionnel camerounais à base de feuilles d'ndole (ou feuilles de manioc) et de pâte d'arachide, souvent servi avec de la viande ou du poisson.", ingredients: "Les feuilles d'ndole sont riches en vitamines et minéraux, et la pâte d'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: ndole20 },
  { id: 41, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru1 },
  { id: 42, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru2 },
  { id: 43, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru3 },
  { id: 44, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru4 },
  { id: 45, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru5 },
  { id: 46, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru6 },
  { id: 47, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru7 },
  { id: 48, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru8 },
  { id: 49, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru9 },
  { id: 50, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru10 },
  { id: 51, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru11 },
  { id: 52, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru12 },
  { id: 53, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru13 },
  { id: 54, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru14 },
  { id: 55, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru15 },
  { id: 56, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru16 },
  { id: 57, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru17 },
  { id: 58, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru18 },
  { id: 59, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru19 },
  { id: 60, nom: 'eru', description: "L'érue est un plat camerounais à base de feuilles de manioc fermentées, souvent servi avec de la viande ou du poisson. C'est un plat riche en saveurs et en histoire.", ingredients: "Les feuilles de manioc sont riches en vitamines et minéraux, et la fermentation ajoute des probiotiques bénéfiques pour la santé. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: eru20 },
  { id: 61, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous1 },
  { id: 62, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous2 },
  { id: 63, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous3 },
  { id: 64, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous4 },
  { id: 65, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous5 },
  { id: 66, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous6 },
  { id: 67, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous7 },
  { id: 68, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous8 },
  { id: 69, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous9 },
  { id: 70, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous10 },
  { id: 71, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous11 },
  { id: 72, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous12 },
  { id: 73, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous13 },
  { id: 74, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous14 },
  { id: 75, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous15 },
  { id: 76, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous16 },
  { id: 77, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous17 },
  { id: 78, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous18 },
  { id: 79, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous19 },
  { id: 80, nom: 'kous_kous', description: "Le kous-kous est un plat à base de semoule de maïs ou de blé, cuit à la vapeur et servi avec une sauce, souvent à base de légumes et de viande.", ingredients: "Le kous-kous est riche en glucides et peut être accompagné de légumes, viande ou poisson, selon les préférences. C'est un plat nourrissant et réconfortant.", imageUrl: kous_kous20 },
  { id: 81, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok1 },
  { id: 82, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok2 },
  { id: 83, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok3 },
  { id: 84, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok4 },
  { id: 85, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok5 },
  { id: 86, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok6 },
  { id: 87, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok7 },
  { id: 88, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok8 },
  { id: 89, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok9 },
  { id: 90, nom: 'okok', description: "L'okok est un plat camerounais à base de feuilles de cocotier, souvent servi avec une sauce à base d'arachides et de la viande ou du poisson.", ingredients: "Les feuilles de cocotier sont riches en fibres et en nutriments, et la sauce à l'arachide ajoute des protéines et des graisses saines. Ce plat est souvent accompagné de riz ou de plantains.", imageUrl: okok10 },
];
