version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: java_food_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NNMINDE12;
    ports:
      - "5433:5432"
    volumes:
      - pgdata_java:/var/lib/postgresql/data

  backend-java:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java_food_manager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: NNMINDE12;
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata_java: